name: "build"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["18.x", "20.x", "22.x", "23.x"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: pnpm
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run test
      - run: pnpm run lint
